### ISSUE TITLE
Why should somone use these?

### ISSUE THREAD

**Issue by SmokinSpectre** [Torbet/Social-Scripts#1]
Hey, I noticed you were using the GitHub Follow/Unfollow script  today as your follower/following count is fluctuating rapidly, Seems pretty cool but what's the point in using them as they basically follow/unfollow random people you don't know?

**Comment by SmokinSpectre** [comment]
> Follow/Unfollow All Users On Page
Do you mean *Stargazers/Watchers* by **Page**?

**Comment by Torbet** [comment]
Hey man! So originally I just made a quick Twitter script because I follow too many people and it clogs up my timeline, GitHub became my testing ground to try and get it right (navigating through pages and tabs), main thing is to unfollow everyone, and then follow from a specific twitter list!

Follow / unfollow is github followers, you can unstar with the other script, I'm not sure what you mean, my bad!

**Comment by SmokinSpectre** [comment]
Cool Scripts I'll give them a try 🙂
> Do you mean Stargazers/Watchers by Page?

Whenever we open the Stargazers tab on a repository it shows a list of people along with a button to follow them.

**Comment by Torbet** [comment]
They're very basic right now, will update the repo when I make them more functional!

Ahh I get what you mean now, the follow ones will act wherever there is a "follow" button, so when you click on a repos stars, the follow one will follow everyone.

If you go to your own stars, unstar script will remove them, so anywhere there is a star button ;)
